name: mdspan version check

on:
  pull_request:
    paths:
      - '.github/workflows/mdspan-version-check.yml'
      - 'tpls/mdspan-hash.txt'
      - 'tpls/mdspan/**'

permissions: read-all

jobs:
  mdspan-version-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    - run: echo "ref=$(cat tpls/mdspan-hash.txt)" >> $GITHUB_ENV
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        repository: kokkos/mdspan
        ref: ${{ env.ref }}
        path: kokkos-mdspan
    - run: |
        rm kokkos-mdspan/include/experimental/mdarray
        rm kokkos-mdspan/include/experimental/mdspan
        diff --brief --recursive tpls/mdspan/include kokkos-mdspan/include
